# Generated by Django 5.1.6 on 2025-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_author_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(upload_to='core/covers/%Y/%m/%d/'),
        ),
    ]
